version: "3"

services:
  near-intent-workshop:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: >
      bash -c "npm install && npm run dev"
    ports:
      - "5174:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=5174
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=host.docker.internal,*.rshare.io,endless-squirrel-47.rshare.io
    restart: unless-stopped
